// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Command specifies the type of command to execute.
public struct Command: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The type of command.
  public var commandType: OneOf_CommandType? = nil

  /// Initialize a new instance of `Command`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Command().with { $0.agentCommand = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case agentCommand = "agentCommand"
    case shellCommand = "shellCommand"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var commandType: OneOf_CommandType? = nil
    let commandTypeCheckAndSet = {
      if commandType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'commandType'"))
      }
      commandType = $0
    }
    if let agentCommand = try container.decodeIfPresent(AgentCommand?.self, forKey: .agentCommand) {
      try commandTypeCheckAndSet(.agentCommand(agentCommand))
    }
    if let shellCommand = try container.decodeIfPresent(ShellCommand?.self, forKey: .shellCommand) {
      try commandTypeCheckAndSet(.shellCommand(shellCommand))
    }
    self.commandType = commandType
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.commandType {
      switch choice {
      case .agentCommand(let value):
        try container.encode(value, forKey: .agentCommand)
      case .shellCommand(let value):
        try container.encode(value, forKey: .shellCommand)
      }
    }
  }

  /// The type of command.
  public enum OneOf_CommandType: Codable, Equatable, Sendable {
    /// AgentCommand specifies a one-time executable program for the agent to
    /// run.
    indirect case agentCommand(AgentCommand?)
    /// ShellCommand is invoked via the agent's command line executor.
    indirect case shellCommand(ShellCommand?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.workloadmanager.v1.Command"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
