// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The result of an execution.
public struct ExecutionResult: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The violation message of an execution.
  public var violationMessage: Swift.String = Swift.String()

  /// The severity of violation.
  public var severity: Swift.String = Swift.String()

  /// The rule that is violated in an evaluation.
  public var rule: Swift.String = Swift.String()

  /// The URL for the documentation of the rule.
  public var documentationUrl: Swift.String = Swift.String()

  /// The resource that violates the rule.
  public var resource: Resource? = nil

  /// The details of violation in an evaluation result.
  public var violationDetails: ViolationDetails? = nil

  /// The commands to remediate the violation.
  public var commands: [Command] = []

  /// Execution result type of the scanned resource.
  public var type: ExecutionResult.Type_ = ExecutionResult.Type_()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ExecutionResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExecutionResult().with { $0.violationMessage = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let violationMessage = CodingKeys(stringValue: "violationMessage")
    static let severity = CodingKeys(stringValue: "severity")
    static let rule = CodingKeys(stringValue: "rule")
    static let documentationUrl = CodingKeys(stringValue: "documentationUrl")
    static let resource = CodingKeys(stringValue: "resource")
    static let violationDetails = CodingKeys(stringValue: "violationDetails")
    static let commands = CodingKeys(stringValue: "commands")
    static let type = CodingKeys(stringValue: "type")

    static let _knownKeys: Set<Swift.String> = [
      "violationMessage",
      "severity",
      "rule",
      "documentationUrl",
      "resource",
      "violationDetails",
      "commands",
      "type",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .violationMessage) {
      self.violationMessage = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .severity) {
      self.severity = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .rule) {
      self.rule = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .documentationUrl) {
      self.documentationUrl = value
    }
    self.resource = try container.decodeIfPresent(Resource.self, forKey: .resource)
    self.violationDetails = try container.decodeIfPresent(
      ViolationDetails.self, forKey: .violationDetails)
    if let value = try container.decodeIfPresent([Command].self, forKey: .commands) {
      self.commands = value
    }
    if let value = try container.decodeIfPresent(ExecutionResult.Type_.self, forKey: .type) {
      self.type = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.violationMessage, forKey: .violationMessage)
    try container.encode(self.severity, forKey: .severity)
    try container.encode(self.rule, forKey: .rule)
    try container.encode(self.documentationUrl, forKey: .documentationUrl)
    try container.encodeIfPresent(self.resource, forKey: .resource)
    try container.encodeIfPresent(self.violationDetails, forKey: .violationDetails)
    try container.encode(self.commands, forKey: .commands)
    try container.encode(self.type, forKey: .type)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Enum of execution result type.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Type_: Codable, Equatable, Hashable, Sendable {
    /// Unknown state.
    case unspecified
    /// Resource successfully passed the rule.
    case passed
    /// Resource violated the rule.
    case violated
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .passed: return 1
      case .violated: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TYPE_UNSPECIFIED"
      case .passed: return "TYPE_PASSED"
      case .violated: return "TYPE_VIOLATED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TYPE_UNSPECIFIED": self = .unspecified
      case "TYPE_PASSED": self = .passed
      case "TYPE_VIOLATED": self = .violated
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .passed
      case 2: self = .violated
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("TYPE_UNSPECIFIED")
      case .passed: return try container.encode("TYPE_PASSED")
      case .violated: return try container.encode("TYPE_VIOLATED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.workloadmanager.v1.ExecutionResult"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
