// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for the ListRules RPC.
public struct ListRulesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The [project] on which to execute the request. The format is:
  ///     projects/{project_id}/locations/{location}
  /// Currently, the pre-defined rules are global available to all projects and
  /// all regions.
  public var parent: Swift.String = Swift.String()

  /// Requested page size. Server may return fewer items than requested.
  /// If unspecified, server will pick an appropriate default.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// A token identifying a page of results the server should return.
  public var pageToken: Swift.String = Swift.String()

  /// Filter based on primary_category, secondary_category.
  public var filter: Swift.String = Swift.String()

  /// The Cloud Storage bucket name for custom rules.
  public var customRulesBucket: Swift.String = Swift.String()

  /// Optional. The evaluation type of the rules will be applied to.
  /// The Cloud Storage bucket name for custom rules.
  public var evaluationType: Evaluation.EvaluationType = Evaluation.EvaluationType()

  /// Initialize a new instance of `ListRulesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListRulesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.workloadmanager.v1.ListRulesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
