// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Resource filter for an evaluation defining the scope of resources to be
/// evaluated.
public struct ResourceFilter: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The scopes of evaluation resource.
  /// Format:
  /// * `projects/{project_id}`
  /// * `folders/{folder_id}`
  /// * `organizations/{organization_id}`
  public var scopes: [Swift.String] = []

  /// The pattern to filter resources by their id
  /// For example, a pattern of ".*prod-cluster.*" will match all resources that
  /// contain "prod-cluster" in their ID.
  public var resourceIdPatterns: [Swift.String] = []

  /// Labels to filter resources by. Each key-value pair in the map must exist
  /// on the resource for it to be included (e.g. VM instance labels).
  /// For example, specifying `{ "env": "prod", "database": "nosql" }` will only
  /// include resources that have labels `env=prod` and `database=nosql`.
  public var inclusionLabels: [Swift.String: Swift.String] = [:]

  /// Filter compute engine resources.
  public var gceInstanceFilter: GceInstanceFilter? = nil

  /// Initialize a new instance of `ResourceFilter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ResourceFilter().with { $0.scopes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.workloadmanager.v1.ResourceFilter"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
