// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Resource filter for an evaluation defining the scope of resources to be
/// evaluated.
public struct ResourceFilter: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The scopes of evaluation resource.
  /// Format:
  /// * `projects/{project_id}`
  /// * `folders/{folder_id}`
  /// * `organizations/{organization_id}`
  public var scopes: [Swift.String] = []

  /// The pattern to filter resources by their id
  /// For example, a pattern of ".*prod-cluster.*" will match all resources that
  /// contain "prod-cluster" in their ID.
  public var resourceIdPatterns: [Swift.String] = []

  /// Labels to filter resources by. Each key-value pair in the map must exist
  /// on the resource for it to be included (e.g. VM instance labels).
  /// For example, specifying `{ "env": "prod", "database": "nosql" }` will only
  /// include resources that have labels `env=prod` and `database=nosql`.
  public var inclusionLabels: [Swift.String: Swift.String] = [:]

  /// Filter compute engine resources.
  public var gceInstanceFilter: GceInstanceFilter? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ResourceFilter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ResourceFilter().with { $0.scopes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let scopes = CodingKeys(stringValue: "scopes")
    static let resourceIdPatterns = CodingKeys(stringValue: "resourceIdPatterns")
    static let inclusionLabels = CodingKeys(stringValue: "inclusionLabels")
    static let gceInstanceFilter = CodingKeys(stringValue: "gceInstanceFilter")

    static let _knownKeys: Set<Swift.String> = [
      "scopes",
      "resourceIdPatterns",
      "inclusionLabels",
      "gceInstanceFilter",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .scopes) {
      self.scopes = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .resourceIdPatterns) {
      self.resourceIdPatterns = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .inclusionLabels)
    {
      self.inclusionLabels = value
    }
    self.gceInstanceFilter = try container.decodeIfPresent(
      GceInstanceFilter.self, forKey: .gceInstanceFilter)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.scopes, forKey: .scopes)
    try container.encode(self.resourceIdPatterns, forKey: .resourceIdPatterns)
    try container.encode(self.inclusionLabels, forKey: .inclusionLabels)
    try container.encodeIfPresent(self.gceInstanceFilter, forKey: .gceInstanceFilter)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.workloadmanager.v1.ResourceFilter"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
