// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Execution result summary per rule.
public struct RuleExecutionResult: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Rule name as plain text like `sap-hana-configured`.
  public var rule: Swift.String = Swift.String()

  /// Output only. The execution status.
  public var state: RuleExecutionResult.State = RuleExecutionResult.State()

  /// Execution message, if any.
  public var message: Swift.String = Swift.String()

  /// Number of violations.
  public var resultCount: Swift.Int64 = Swift.Int64()

  /// Number of total scanned resources.
  public var scannedResourceCount: Swift.Int64 = Swift.Int64()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RuleExecutionResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RuleExecutionResult().with { $0.rule = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let rule = CodingKeys(stringValue: "rule")
    static let state = CodingKeys(stringValue: "state")
    static let message = CodingKeys(stringValue: "message")
    static let resultCount = CodingKeys(stringValue: "resultCount")
    static let scannedResourceCount = CodingKeys(stringValue: "scannedResourceCount")

    static let _knownKeys: Set<Swift.String> = [
      "rule",
      "state",
      "message",
      "resultCount",
      "scannedResourceCount",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .rule) {
      self.rule = value
    }
    if let value = try container.decodeIfPresent(RuleExecutionResult.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .message) {
      self.message = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .resultCount) {
      self.resultCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .scannedResourceCount) {
      self.scannedResourceCount = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.rule, forKey: .rule)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.message, forKey: .message)
    try container.encode(self.resultCount, forKey: .resultCount)
    try container.encode(self.scannedResourceCount, forKey: .scannedResourceCount)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Possible states of a rule execution like SUCCESS, FAILURE, etc.
  public enum State: Codable, Equatable, Sendable {
    /// Unknown state
    case unspecified
    /// Execution completed successfully
    case success
    /// Execution completed with failures
    case failure
    /// Execution was not executed
    case skipped
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .success: return 1
      case .failure: return 2
      case .skipped: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .success: return "STATE_SUCCESS"
      case .failure: return "STATE_FAILURE"
      case .skipped: return "STATE_SKIPPED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "STATE_SUCCESS": self = .success
      case "STATE_FAILURE": self = .failure
      case "STATE_SKIPPED": self = .skipped
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .success
      case 2: self = .failure
      case 3: self = .skipped
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .success: return try container.encode("STATE_SUCCESS")
      case .failure: return try container.encode("STATE_FAILURE")
      case .skipped: return try container.encode("STATE_SKIPPED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.workloadmanager.v1.RuleExecutionResult"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
