// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The violation in an evaluation result.
public struct ViolationDetails: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The name of the asset.
  public var asset: Swift.String = Swift.String()

  /// The service account associated with the resource.
  public var serviceAccount: Swift.String = Swift.String()

  /// Details of the violation.
  public var observed: [Swift.String: Swift.String] = [:]

  /// Output only. The rule output of the violation.
  public var ruleOutput: [RuleOutput] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ViolationDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ViolationDetails().with { $0.asset = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let asset = CodingKeys(stringValue: "asset")
    static let serviceAccount = CodingKeys(stringValue: "serviceAccount")
    static let observed = CodingKeys(stringValue: "observed")
    static let ruleOutput = CodingKeys(stringValue: "ruleOutput")

    static let _knownKeys: Set<Swift.String> = [
      "asset",
      "serviceAccount",
      "observed",
      "ruleOutput",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .asset) {
      self.asset = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAccount) {
      self.serviceAccount = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .observed)
    {
      self.observed = value
    }
    if let value = try container.decodeIfPresent([RuleOutput].self, forKey: .ruleOutput) {
      self.ruleOutput = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.asset, forKey: .asset)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encode(self.observed, forKey: .observed)
    try container.encode(self.ruleOutput, forKey: .ruleOutput)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.workloadmanager.v1.ViolationDetails"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
