// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// The Workload Manager provides various tools to deploy, validate and observe
/// your workloads running on Google Cloud.
///
/// @Snippet(path: "WorkloadManagerQuickstart")
public final class WorkloadManagerClient: Clients.WorkloadManagerProtocol, Sendable {
  let inner: any Clients.WorkloadManagerStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `WorkloadManagerClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.WorkloadManagerStub = try Clients.WorkloadManagerTransport(options)
    inner = Clients.WorkloadManagerRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.WorkloadManagerLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists Evaluations in a given project and location.
  ///
  /// @Snippet(path: "WorkloadManager_ListEvaluations")
  public func listEvaluations(
    request: ListEvaluationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkloadManagerV1.ListEvaluationsResponse {
    try await self.inner.listEvaluations(request: request, options: options)
  }

  /// Lists Evaluations in a given project and location.
  ///
  /// @Snippet(path: "WorkloadManager_ListEvaluations")
  public func listEvaluations(
    byItem: ListEvaluationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Evaluation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudWorkloadManagerV1.ListEvaluationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listEvaluations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single Evaluation.
  ///
  /// @Snippet(path: "WorkloadManager_GetEvaluation")
  public func getEvaluation(
    request: GetEvaluationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkloadManagerV1.Evaluation {
    try await self.inner.getEvaluation(request: request, options: options)
  }

  /// Creates a new Evaluation in a given project and location.
  ///
  /// @Snippet(path: "WorkloadManager_CreateEvaluation")
  public func createEvaluation(
    request: CreateEvaluationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createEvaluation(request: request, options: options)
  }

  /// Creates a new Evaluation in a given project and location.
  ///
  /// @Snippet(path: "WorkloadManager_CreateEvaluation")
  public func createEvaluation(
    withPolling: CreateEvaluationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Evaluation> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Evaluation>.State in
      return try op._extractStatus(Evaluation.self)
    }
    let rawOp = try await self.createEvaluation(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Evaluation>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the parameters of a single Evaluation.
  ///
  /// @Snippet(path: "WorkloadManager_UpdateEvaluation")
  public func updateEvaluation(
    request: UpdateEvaluationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateEvaluation(request: request, options: options)
  }

  /// Updates the parameters of a single Evaluation.
  ///
  /// @Snippet(path: "WorkloadManager_UpdateEvaluation")
  public func updateEvaluation(
    withPolling: UpdateEvaluationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Evaluation> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Evaluation>.State in
      return try op._extractStatus(Evaluation.self)
    }
    let rawOp = try await self.updateEvaluation(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Evaluation>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single Evaluation.
  ///
  /// @Snippet(path: "WorkloadManager_DeleteEvaluation")
  public func deleteEvaluation(
    request: DeleteEvaluationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteEvaluation(request: request, options: options)
  }

  /// Deletes a single Evaluation.
  ///
  /// @Snippet(path: "WorkloadManager_DeleteEvaluation")
  public func deleteEvaluation(
    withPolling: DeleteEvaluationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteEvaluation(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists Executions in a given project and location.
  ///
  /// @Snippet(path: "WorkloadManager_ListExecutions")
  public func listExecutions(
    request: ListExecutionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkloadManagerV1.ListExecutionsResponse {
    try await self.inner.listExecutions(request: request, options: options)
  }

  /// Lists Executions in a given project and location.
  ///
  /// @Snippet(path: "WorkloadManager_ListExecutions")
  public func listExecutions(
    byItem: ListExecutionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Execution, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudWorkloadManagerV1.ListExecutionsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listExecutions(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single Execution.
  ///
  /// @Snippet(path: "WorkloadManager_GetExecution")
  public func getExecution(
    request: GetExecutionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkloadManagerV1.Execution {
    try await self.inner.getExecution(request: request, options: options)
  }

  /// Creates a new Execution in a given project and location.
  ///
  /// @Snippet(path: "WorkloadManager_RunEvaluation")
  public func runEvaluation(
    request: RunEvaluationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.runEvaluation(request: request, options: options)
  }

  /// Creates a new Execution in a given project and location.
  ///
  /// @Snippet(path: "WorkloadManager_RunEvaluation")
  public func runEvaluation(
    withPolling: RunEvaluationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Execution> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Execution>.State in
      return try op._extractStatus(Execution.self)
    }
    let rawOp = try await self.runEvaluation(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Execution>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single Execution.
  ///
  /// @Snippet(path: "WorkloadManager_DeleteExecution")
  public func deleteExecution(
    request: DeleteExecutionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteExecution(request: request, options: options)
  }

  /// Deletes a single Execution.
  ///
  /// @Snippet(path: "WorkloadManager_DeleteExecution")
  public func deleteExecution(
    withPolling: DeleteExecutionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteExecution(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists the result of a single evaluation.
  ///
  /// @Snippet(path: "WorkloadManager_ListExecutionResults")
  public func listExecutionResults(
    request: ListExecutionResultsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkloadManagerV1.ListExecutionResultsResponse {
    try await self.inner.listExecutionResults(request: request, options: options)
  }

  /// Lists the result of a single evaluation.
  ///
  /// @Snippet(path: "WorkloadManager_ListExecutionResults")
  public func listExecutionResults(
    byItem: ListExecutionResultsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ExecutionResult, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudWorkloadManagerV1.ListExecutionResultsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listExecutionResults(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Lists rules in a given project.
  ///
  /// @Snippet(path: "WorkloadManager_ListRules")
  public func listRules(
    request: ListRulesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkloadManagerV1.ListRulesResponse {
    try await self.inner.listRules(request: request, options: options)
  }

  /// List all scanned resources for a single Execution.
  ///
  /// @Snippet(path: "WorkloadManager_ListScannedResources")
  public func listScannedResources(
    request: ListScannedResourcesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkloadManagerV1.ListScannedResourcesResponse {
    try await self.inner.listScannedResources(request: request, options: options)
  }

  /// List all scanned resources for a single Execution.
  ///
  /// @Snippet(path: "WorkloadManager_ListScannedResources")
  public func listScannedResources(
    byItem: ListScannedResourcesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ScannedResource, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudWorkloadManagerV1.ListScannedResourcesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listScannedResources(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Lists information about the supported locations for this service.
  /// This method can be called in two ways:
  ///
  /// *   **List all public locations:** Use the path `GET /v1/locations`.
  /// *   **List project-visible locations:** Use the path
  /// `GET /v1/projects/{project_id}/locations`. This may include public
  /// locations as well as private or other locations specifically visible
  /// to the project.
  ///
  /// @Snippet(path: "WorkloadManager_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  /// This method can be called in two ways:
  ///
  /// *   **List all public locations:** Use the path `GET /v1/locations`.
  /// *   **List project-visible locations:** Use the path
  /// `GET /v1/projects/{project_id}/locations`. This may include public
  /// locations as well as private or other locations specifically visible
  /// to the project.
  ///
  /// @Snippet(path: "WorkloadManager_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "WorkloadManager_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "WorkloadManager_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "WorkloadManager_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "WorkloadManager_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "WorkloadManager_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "WorkloadManager_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `WorkloadManagerClient`.
  ///
  /// To mock `WorkloadManagerClient` change your functions to receive
  /// `some WorkloadManagerProtocol` or `any WorkloadManagerProtocol`
  /// and pass a mock implementation in your tests.
  public protocol WorkloadManagerProtocol {
    /// See `WorkloadManagerClient.listEvaluations`.
    func listEvaluations(request: ListEvaluationsRequest) async throws
      -> GoogleCloudWorkloadManagerV1.ListEvaluationsResponse

    /// See `WorkloadManagerClient.listEvaluations`.
    func listEvaluations(
      byItem: ListEvaluationsRequest
    ) throws -> any AsyncSequence<Evaluation, Swift.Error>

    /// See `WorkloadManagerClient.listEvaluations`.
    func listEvaluations(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Evaluation, Swift.Error>

    /// See `WorkloadManagerClient.getEvaluation`.
    func getEvaluation(request: GetEvaluationRequest) async throws
      -> GoogleCloudWorkloadManagerV1.Evaluation

    /// See `WorkloadManagerClient.getEvaluation`.
    func getEvaluation(
      name: Swift.String,
    ) async throws -> GoogleCloudWorkloadManagerV1.Evaluation

    /// See `WorkloadManagerClient.createEvaluation`.
    func createEvaluation(request: CreateEvaluationRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `WorkloadManagerClient.createEvaluation`.
    func createEvaluation(withPolling: CreateEvaluationRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Evaluation>

    /// See `WorkloadManagerClient.createEvaluation`.
    func createEvaluation(
      parent: Swift.String,
      evaluation: Evaluation?,
      evaluationId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Evaluation>

    /// See `WorkloadManagerClient.updateEvaluation`.
    func updateEvaluation(request: UpdateEvaluationRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `WorkloadManagerClient.updateEvaluation`.
    func updateEvaluation(withPolling: UpdateEvaluationRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Evaluation>

    /// See `WorkloadManagerClient.updateEvaluation`.
    func updateEvaluation(
      evaluation: Evaluation?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Evaluation>

    /// See `WorkloadManagerClient.deleteEvaluation`.
    func deleteEvaluation(request: DeleteEvaluationRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `WorkloadManagerClient.deleteEvaluation`.
    func deleteEvaluation(withPolling: DeleteEvaluationRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Swift.Void>

    /// See `WorkloadManagerClient.deleteEvaluation`.
    func deleteEvaluation(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `WorkloadManagerClient.listExecutions`.
    func listExecutions(request: ListExecutionsRequest) async throws
      -> GoogleCloudWorkloadManagerV1.ListExecutionsResponse

    /// See `WorkloadManagerClient.listExecutions`.
    func listExecutions(
      byItem: ListExecutionsRequest
    ) throws -> any AsyncSequence<Execution, Swift.Error>

    /// See `WorkloadManagerClient.listExecutions`.
    func listExecutions(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Execution, Swift.Error>

    /// See `WorkloadManagerClient.getExecution`.
    func getExecution(request: GetExecutionRequest) async throws
      -> GoogleCloudWorkloadManagerV1.Execution

    /// See `WorkloadManagerClient.getExecution`.
    func getExecution(
      name: Swift.String,
    ) async throws -> GoogleCloudWorkloadManagerV1.Execution

    /// See `WorkloadManagerClient.runEvaluation`.
    func runEvaluation(request: RunEvaluationRequest) async throws -> GoogleLongRunning.Operation

    /// See `WorkloadManagerClient.runEvaluation`.
    func runEvaluation(withPolling: RunEvaluationRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Execution>

    /// See `WorkloadManagerClient.runEvaluation`.
    func runEvaluation(
      name: Swift.String,
      execution: Execution?,
      executionId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Execution>

    /// See `WorkloadManagerClient.deleteExecution`.
    func deleteExecution(request: DeleteExecutionRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `WorkloadManagerClient.deleteExecution`.
    func deleteExecution(withPolling: DeleteExecutionRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Swift.Void>

    /// See `WorkloadManagerClient.deleteExecution`.
    func deleteExecution(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `WorkloadManagerClient.listExecutionResults`.
    func listExecutionResults(request: ListExecutionResultsRequest) async throws
      -> GoogleCloudWorkloadManagerV1.ListExecutionResultsResponse

    /// See `WorkloadManagerClient.listExecutionResults`.
    func listExecutionResults(
      byItem: ListExecutionResultsRequest
    ) throws -> any AsyncSequence<ExecutionResult, Swift.Error>

    /// See `WorkloadManagerClient.listExecutionResults`.
    func listExecutionResults(
      parent: Swift.String,
    ) throws -> any AsyncSequence<ExecutionResult, Swift.Error>

    /// See `WorkloadManagerClient.listRules`.
    func listRules(request: ListRulesRequest) async throws
      -> GoogleCloudWorkloadManagerV1.ListRulesResponse

    /// See `WorkloadManagerClient.listRules`.
    func listRules(
      parent: Swift.String,
    ) async throws -> GoogleCloudWorkloadManagerV1.ListRulesResponse

    /// See `WorkloadManagerClient.listScannedResources`.
    func listScannedResources(request: ListScannedResourcesRequest) async throws
      -> GoogleCloudWorkloadManagerV1.ListScannedResourcesResponse

    /// See `WorkloadManagerClient.listScannedResources`.
    func listScannedResources(
      byItem: ListScannedResourcesRequest
    ) throws -> any AsyncSequence<ScannedResource, Swift.Error>

    /// See `WorkloadManagerClient.listScannedResources`.
    func listScannedResources(
      parent: Swift.String,
    ) throws -> any AsyncSequence<ScannedResource, Swift.Error>

    /// See `WorkloadManagerClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `WorkloadManagerClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `WorkloadManagerClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `WorkloadManagerClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `WorkloadManagerClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `WorkloadManagerClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `WorkloadManagerClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `WorkloadManagerClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `WorkloadManagerClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `WorkloadManagerClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `WorkloadManagerClient.listEvaluations`.
    func listEvaluations(
      request: ListEvaluationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkloadManagerV1.ListEvaluationsResponse

    /// See `WorkloadManagerClient.listEvaluations`.
    func listEvaluations(
      byItem: ListEvaluationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Evaluation, Swift.Error>

    /// See `WorkloadManagerClient.getEvaluation`.
    func getEvaluation(
      request: GetEvaluationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkloadManagerV1.Evaluation

    /// See `WorkloadManagerClient.createEvaluation`.
    func createEvaluation(
      request: CreateEvaluationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkloadManagerClient.createEvaluation`.
    func createEvaluation(
      withPolling: CreateEvaluationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Evaluation>

    /// See `WorkloadManagerClient.updateEvaluation`.
    func updateEvaluation(
      request: UpdateEvaluationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkloadManagerClient.updateEvaluation`.
    func updateEvaluation(
      withPolling: UpdateEvaluationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Evaluation>

    /// See `WorkloadManagerClient.deleteEvaluation`.
    func deleteEvaluation(
      request: DeleteEvaluationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkloadManagerClient.deleteEvaluation`.
    func deleteEvaluation(
      withPolling: DeleteEvaluationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `WorkloadManagerClient.listExecutions`.
    func listExecutions(
      request: ListExecutionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkloadManagerV1.ListExecutionsResponse

    /// See `WorkloadManagerClient.listExecutions`.
    func listExecutions(
      byItem: ListExecutionsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Execution, Swift.Error>

    /// See `WorkloadManagerClient.getExecution`.
    func getExecution(
      request: GetExecutionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkloadManagerV1.Execution

    /// See `WorkloadManagerClient.runEvaluation`.
    func runEvaluation(
      request: RunEvaluationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkloadManagerClient.runEvaluation`.
    func runEvaluation(
      withPolling: RunEvaluationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Execution>

    /// See `WorkloadManagerClient.deleteExecution`.
    func deleteExecution(
      request: DeleteExecutionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WorkloadManagerClient.deleteExecution`.
    func deleteExecution(
      withPolling: DeleteExecutionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `WorkloadManagerClient.listExecutionResults`.
    func listExecutionResults(
      request: ListExecutionResultsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkloadManagerV1.ListExecutionResultsResponse

    /// See `WorkloadManagerClient.listExecutionResults`.
    func listExecutionResults(
      byItem: ListExecutionResultsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ExecutionResult, Swift.Error>

    /// See `WorkloadManagerClient.listRules`.
    func listRules(
      request: ListRulesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkloadManagerV1.ListRulesResponse

    /// See `WorkloadManagerClient.listScannedResources`.
    func listScannedResources(
      request: ListScannedResourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkloadManagerV1.ListScannedResourcesResponse

    /// See `WorkloadManagerClient.listScannedResources`.
    func listScannedResources(
      byItem: ListScannedResourcesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ScannedResource, Swift.Error>

    /// See `WorkloadManagerClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `WorkloadManagerClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `WorkloadManagerClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `WorkloadManagerClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `WorkloadManagerClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `WorkloadManagerClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `WorkloadManagerClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.WorkloadManagerProtocol {
  public func listEvaluations(request: ListEvaluationsRequest) async throws
    -> GoogleCloudWorkloadManagerV1.ListEvaluationsResponse
  {
    try await self.listEvaluations(request: request, options: .init())
  }

  public func listEvaluations(
    request: ListEvaluationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkloadManagerV1.ListEvaluationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listEvaluations(
    byItem: ListEvaluationsRequest
  ) throws -> any AsyncSequence<Evaluation, Swift.Error> {
    try self.listEvaluations(byItem: byItem, options: .init())
  }

  public func listEvaluations(
    byItem: ListEvaluationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Evaluation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudWorkloadManagerV1.ListEvaluationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listEvaluations(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Evaluation, Swift.Error> {
    let request = ListEvaluationsRequest().with {
      $0.parent = parent
    }
    return try self.listEvaluations(byItem: request)
  }

  public func getEvaluation(request: GetEvaluationRequest) async throws
    -> GoogleCloudWorkloadManagerV1.Evaluation
  {
    try await self.getEvaluation(request: request, options: .init())
  }

  public func getEvaluation(
    request: GetEvaluationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkloadManagerV1.Evaluation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getEvaluation(
    name: Swift.String,
  ) async throws -> GoogleCloudWorkloadManagerV1.Evaluation {
    let request = GetEvaluationRequest().with {
      $0.name = name
    }
    return try await self.getEvaluation(request: request)
  }

  public func createEvaluation(request: CreateEvaluationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createEvaluation(request: request, options: .init())
  }

  public func createEvaluation(
    request: CreateEvaluationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createEvaluation(withPolling: CreateEvaluationRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Evaluation>
  {
    try await self.createEvaluation(withPolling: withPolling, options: .init())
  }

  public func createEvaluation(
    withPolling: CreateEvaluationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Evaluation> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Evaluation>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createEvaluation(
    parent: Swift.String,
    evaluation: Evaluation?,
    evaluationId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Evaluation> {
    let request = CreateEvaluationRequest().with {
      $0.parent = parent
      $0.evaluation = evaluation
      $0.evaluationId = evaluationId
    }
    return try await self.createEvaluation(withPolling: request)
  }

  public func updateEvaluation(request: UpdateEvaluationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateEvaluation(request: request, options: .init())
  }

  public func updateEvaluation(
    request: UpdateEvaluationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateEvaluation(withPolling: UpdateEvaluationRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Evaluation>
  {
    try await self.updateEvaluation(withPolling: withPolling, options: .init())
  }

  public func updateEvaluation(
    withPolling: UpdateEvaluationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Evaluation> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Evaluation>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateEvaluation(
    evaluation: Evaluation?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Evaluation> {
    let request = UpdateEvaluationRequest().with {
      $0.evaluation = evaluation
      $0.updateMask = updateMask
    }
    return try await self.updateEvaluation(withPolling: request)
  }

  public func deleteEvaluation(request: DeleteEvaluationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteEvaluation(request: request, options: .init())
  }

  public func deleteEvaluation(
    request: DeleteEvaluationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteEvaluation(withPolling: DeleteEvaluationRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Swift.Void>
  {
    try await self.deleteEvaluation(withPolling: withPolling, options: .init())
  }

  public func deleteEvaluation(
    withPolling: DeleteEvaluationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteEvaluation(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteEvaluationRequest().with {
      $0.name = name
    }
    return try await self.deleteEvaluation(withPolling: request)
  }

  public func listExecutions(request: ListExecutionsRequest) async throws
    -> GoogleCloudWorkloadManagerV1.ListExecutionsResponse
  {
    try await self.listExecutions(request: request, options: .init())
  }

  public func listExecutions(
    request: ListExecutionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkloadManagerV1.ListExecutionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listExecutions(
    byItem: ListExecutionsRequest
  ) throws -> any AsyncSequence<Execution, Swift.Error> {
    try self.listExecutions(byItem: byItem, options: .init())
  }

  public func listExecutions(
    byItem: ListExecutionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Execution, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudWorkloadManagerV1.ListExecutionsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listExecutions(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Execution, Swift.Error> {
    let request = ListExecutionsRequest().with {
      $0.parent = parent
    }
    return try self.listExecutions(byItem: request)
  }

  public func getExecution(request: GetExecutionRequest) async throws
    -> GoogleCloudWorkloadManagerV1.Execution
  {
    try await self.getExecution(request: request, options: .init())
  }

  public func getExecution(
    request: GetExecutionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkloadManagerV1.Execution {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getExecution(
    name: Swift.String,
  ) async throws -> GoogleCloudWorkloadManagerV1.Execution {
    let request = GetExecutionRequest().with {
      $0.name = name
    }
    return try await self.getExecution(request: request)
  }

  public func runEvaluation(request: RunEvaluationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.runEvaluation(request: request, options: .init())
  }

  public func runEvaluation(
    request: RunEvaluationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func runEvaluation(withPolling: RunEvaluationRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Execution>
  {
    try await self.runEvaluation(withPolling: withPolling, options: .init())
  }

  public func runEvaluation(
    withPolling: RunEvaluationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Execution> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Execution>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func runEvaluation(
    name: Swift.String,
    execution: Execution?,
    executionId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Execution> {
    let request = RunEvaluationRequest().with {
      $0.name = name
      $0.execution = execution
      $0.executionId = executionId
    }
    return try await self.runEvaluation(withPolling: request)
  }

  public func deleteExecution(request: DeleteExecutionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteExecution(request: request, options: .init())
  }

  public func deleteExecution(
    request: DeleteExecutionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteExecution(withPolling: DeleteExecutionRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Swift.Void>
  {
    try await self.deleteExecution(withPolling: withPolling, options: .init())
  }

  public func deleteExecution(
    withPolling: DeleteExecutionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteExecution(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteExecutionRequest().with {
      $0.name = name
    }
    return try await self.deleteExecution(withPolling: request)
  }

  public func listExecutionResults(request: ListExecutionResultsRequest) async throws
    -> GoogleCloudWorkloadManagerV1.ListExecutionResultsResponse
  {
    try await self.listExecutionResults(request: request, options: .init())
  }

  public func listExecutionResults(
    request: ListExecutionResultsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkloadManagerV1.ListExecutionResultsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listExecutionResults(
    byItem: ListExecutionResultsRequest
  ) throws -> any AsyncSequence<ExecutionResult, Swift.Error> {
    try self.listExecutionResults(byItem: byItem, options: .init())
  }

  public func listExecutionResults(
    byItem: ListExecutionResultsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ExecutionResult, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudWorkloadManagerV1.ListExecutionResultsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listExecutionResults(
    parent: Swift.String,
  ) throws -> any AsyncSequence<ExecutionResult, Swift.Error> {
    let request = ListExecutionResultsRequest().with {
      $0.parent = parent
    }
    return try self.listExecutionResults(byItem: request)
  }

  public func listRules(request: ListRulesRequest) async throws
    -> GoogleCloudWorkloadManagerV1.ListRulesResponse
  {
    try await self.listRules(request: request, options: .init())
  }

  public func listRules(
    request: ListRulesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkloadManagerV1.ListRulesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listRules(
    parent: Swift.String,
  ) async throws -> GoogleCloudWorkloadManagerV1.ListRulesResponse {
    let request = ListRulesRequest().with {
      $0.parent = parent
    }
    return try await self.listRules(request: request)
  }

  public func listScannedResources(request: ListScannedResourcesRequest) async throws
    -> GoogleCloudWorkloadManagerV1.ListScannedResourcesResponse
  {
    try await self.listScannedResources(request: request, options: .init())
  }

  public func listScannedResources(
    request: ListScannedResourcesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWorkloadManagerV1.ListScannedResourcesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listScannedResources(
    byItem: ListScannedResourcesRequest
  ) throws -> any AsyncSequence<ScannedResource, Swift.Error> {
    try self.listScannedResources(byItem: byItem, options: .init())
  }

  public func listScannedResources(
    byItem: ListScannedResourcesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ScannedResource, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudWorkloadManagerV1.ListScannedResourcesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listScannedResources(
    parent: Swift.String,
  ) throws -> any AsyncSequence<ScannedResource, Swift.Error> {
    let request = ListScannedResourcesRequest().with {
      $0.parent = parent
    }
    return try self.listScannedResources(byItem: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
